# country_lookup.py
# Dictionary: FAOSTAT "Area" name -> (ISO3 code, continent)
# Continents follow the same convention as the plan (Our World in Data):
# Russia = Europe; Turkey, Armenia, Azerbaijan, Georgia = Asia; Cyprus = Europe.
# The aggregate "China" is left out on purpose (we already removed it).

country_info = {
    'Afghanistan': ('AFG', 'Asia'),
    'Albania': ('ALB', 'Europe'),
    'Algeria': ('DZA', 'Africa'),
    'Angola': ('AGO', 'Africa'),
    'Antigua and Barbuda': ('ATG', 'North America'),
    'Argentina': ('ARG', 'South America'),
    'Armenia': ('ARM', 'Asia'),
    'Australia': ('AUS', 'Oceania'),
    'Austria': ('AUT', 'Europe'),
    'Azerbaijan': ('AZE', 'Asia'),
    'Bahamas': ('BHS', 'North America'),
    'Bahrain': ('BHR', 'Asia'),
    'Bangladesh': ('BGD', 'Asia'),
    'Barbados': ('BRB', 'North America'),
    'Belarus': ('BLR', 'Europe'),
    'Belgium': ('BEL', 'Europe'),
    'Belize': ('BLZ', 'North America'),
    'Bhutan': ('BTN', 'Asia'),
    'Bolivia (Plurinational State of)': ('BOL', 'South America'),
    'Bosnia and Herzegovina': ('BIH', 'Europe'),
    'Botswana': ('BWA', 'Africa'),
    'Brazil': ('BRA', 'South America'),
    'Bulgaria': ('BGR', 'Europe'),
    'Burkina Faso': ('BFA', 'Africa'),
    'Cabo Verde': ('CPV', 'Africa'),
    'Cambodia': ('KHM', 'Asia'),
    'Cameroon': ('CMR', 'Africa'),
    'Canada': ('CAN', 'North America'),
    'Chile': ('CHL', 'South America'),
    'China, Hong Kong SAR': ('HKG', 'Asia'),
    'China, Macao SAR': ('MAC', 'Asia'),
    'China, Taiwan Province of': ('TWN', 'Asia'),
    'China, mainland': ('CHN', 'Asia'),
    'Colombia': ('COL', 'South America'),
    'Comoros': ('COM', 'Africa'),
    'Congo': ('COG', 'Africa'),
    'Costa Rica': ('CRI', 'North America'),
    'Croatia': ('HRV', 'Europe'),
    'Cuba': ('CUB', 'North America'),
    'Cyprus': ('CYP', 'Europe'),
    'Czechia': ('CZE', 'Europe'),
    "Côte d'Ivoire": ('CIV', 'Africa'),
    "Democratic People's Republic of Korea": ('PRK', 'Asia'),
    'Democratic Republic of the Congo': ('COD', 'Africa'),
    'Denmark': ('DNK', 'Europe'),
    'Djibouti': ('DJI', 'Africa'),
    'Dominican Republic': ('DOM', 'North America'),
    'Ecuador': ('ECU', 'South America'),
    'Egypt': ('EGY', 'Africa'),
    'El Salvador': ('SLV', 'North America'),
    'Estonia': ('EST', 'Europe'),
    'Eswatini': ('SWZ', 'Africa'),
    'Ethiopia': ('ETH', 'Africa'),
    'Fiji': ('FJI', 'Oceania'),
    'Finland': ('FIN', 'Europe'),
    'France': ('FRA', 'Europe'),
    'French Polynesia': ('PYF', 'Oceania'),
    'Gabon': ('GAB', 'Africa'),
    'Gambia': ('GMB', 'Africa'),
    'Georgia': ('GEO', 'Asia'),
    'Germany': ('DEU', 'Europe'),
    'Ghana': ('GHA', 'Africa'),
    'Greece': ('GRC', 'Europe'),
    'Grenada': ('GRD', 'North America'),
    'Guatemala': ('GTM', 'North America'),
    'Guinea': ('GIN', 'Africa'),
    'Guinea-Bissau': ('GNB', 'Africa'),
    'Guyana': ('GUY', 'South America'),
    'Haiti': ('HTI', 'North America'),
    'Honduras': ('HND', 'North America'),
    'Hungary': ('HUN', 'Europe'),
    'Iceland': ('ISL', 'Europe'),
    'India': ('IND', 'Asia'),
    'Indonesia': ('IDN', 'Asia'),
    'Iran (Islamic Republic of)': ('IRN', 'Asia'),
    'Iraq': ('IRQ', 'Asia'),
    'Ireland': ('IRL', 'Europe'),
    'Israel': ('ISR', 'Asia'),
    'Italy': ('ITA', 'Europe'),
    'Jamaica': ('JAM', 'North America'),
    'Jordan': ('JOR', 'Asia'),
    'Kazakhstan': ('KAZ', 'Asia'),
    'Kenya': ('KEN', 'Africa'),
    'Kiribati': ('KIR', 'Oceania'),
    'Kuwait': ('KWT', 'Asia'),
    'Kyrgyzstan': ('KGZ', 'Asia'),
    "Lao People's Democratic Republic": ('LAO', 'Asia'),
    'Latvia': ('LVA', 'Europe'),
    'Lebanon': ('LBN', 'Asia'),
    'Lesotho': ('LSO', 'Africa'),
    'Liberia': ('LBR', 'Africa'),
    'Libya': ('LBY', 'Africa'),
    'Lithuania': ('LTU', 'Europe'),
    'Luxembourg': ('LUX', 'Europe'),
    'Madagascar': ('MDG', 'Africa'),
    'Malawi': ('MWI', 'Africa'),
    'Malaysia': ('MYS', 'Asia'),
    'Maldives': ('MDV', 'Asia'),
    'Malta': ('MLT', 'Europe'),
    'Marshall Islands': ('MHL', 'Oceania'),
    'Mauritania': ('MRT', 'Africa'),
    'Mauritius': ('MUS', 'Africa'),
    'Mexico': ('MEX', 'North America'),
    'Micronesia (Federated States of)': ('FSM', 'Oceania'),
    'Mongolia': ('MNG', 'Asia'),
    'Montenegro': ('MNE', 'Europe'),
    'Morocco': ('MAR', 'Africa'),
    'Mozambique': ('MOZ', 'Africa'),
    'Myanmar': ('MMR', 'Asia'),
    'Namibia': ('NAM', 'Africa'),
    'Naoero': ('NRU', 'Oceania'),
    'Nepal': ('NPL', 'Asia'),
    'Netherlands (Kingdom of the)': ('NLD', 'Europe'),
    'New Caledonia': ('NCL', 'Oceania'),
    'New Zealand': ('NZL', 'Oceania'),
    'Nicaragua': ('NIC', 'North America'),
    'Niger': ('NER', 'Africa'),
    'Nigeria': ('NGA', 'Africa'),
    'North Macedonia': ('MKD', 'Europe'),
    'Norway': ('NOR', 'Europe'),
    'Oman': ('OMN', 'Asia'),
    'Pakistan': ('PAK', 'Asia'),
    'Panama': ('PAN', 'North America'),
    'Papua New Guinea': ('PNG', 'Oceania'),
    'Paraguay': ('PRY', 'South America'),
    'Peru': ('PER', 'South America'),
    'Philippines': ('PHL', 'Asia'),
    'Poland': ('POL', 'Europe'),
    'Portugal': ('PRT', 'Europe'),
    'Qatar': ('QAT', 'Asia'),
    'Republic of Korea': ('KOR', 'Asia'),
    'Republic of Moldova': ('MDA', 'Europe'),
    'Romania': ('ROU', 'Europe'),
    'Russian Federation': ('RUS', 'Europe'),
    'Rwanda': ('RWA', 'Africa'),
    'Saint Kitts and Nevis': ('KNA', 'North America'),
    'Saint Lucia': ('LCA', 'North America'),
    'Saint Vincent and the Grenadines': ('VCT', 'North America'),
    'Samoa': ('WSM', 'Oceania'),
    'Sao Tome and Principe': ('STP', 'Africa'),
    'Saudi Arabia': ('SAU', 'Asia'),
    'Senegal': ('SEN', 'Africa'),
    'Serbia': ('SRB', 'Europe'),
    'Seychelles': ('SYC', 'Africa'),
    'Sierra Leone': ('SLE', 'Africa'),
    'Slovakia': ('SVK', 'Europe'),
    'Slovenia': ('SVN', 'Europe'),
    'Solomon Islands': ('SLB', 'Oceania'),
    'South Africa': ('ZAF', 'Africa'),
    'Spain': ('ESP', 'Europe'),
    'Sri Lanka': ('LKA', 'Asia'),
    'Suriname': ('SUR', 'South America'),
    'Sweden': ('SWE', 'Europe'),
    'Switzerland': ('CHE', 'Europe'),
    'Syrian Arab Republic': ('SYR', 'Asia'),
    'Tajikistan': ('TJK', 'Asia'),
    'Thailand': ('THA', 'Asia'),
    'Timor-Leste': ('TLS', 'Asia'),
    'Tonga': ('TON', 'Oceania'),
    'Trinidad and Tobago': ('TTO', 'North America'),
    'Tunisia': ('TUN', 'Africa'),
    'Turkmenistan': ('TKM', 'Asia'),
    'Tuvalu': ('TUV', 'Oceania'),
    'Türkiye': ('TUR', 'Asia'),
    'Uganda': ('UGA', 'Africa'),
    'Ukraine': ('UKR', 'Europe'),
    'United Arab Emirates': ('ARE', 'Asia'),
    'United Kingdom of Great Britain and Northern Ireland': ('GBR', 'Europe'),
    'United Republic of Tanzania': ('TZA', 'Africa'),
    'United States of America': ('USA', 'North America'),
    'Uruguay': ('URY', 'South America'),
    'Uzbekistan': ('UZB', 'Asia'),
    'Vanuatu': ('VUT', 'Oceania'),
    'Venezuela (Bolivarian Republic of)': ('VEN', 'South America'),
    'Viet Nam': ('VNM', 'Asia'),
    'Yemen': ('YEM', 'Asia'),
    'Zambia': ('ZMB', 'Africa'),
    'Zimbabwe': ('ZWE', 'Africa'),
}
